author: "Mbadiwe Nnaemeka Ronald <ron2tele@gmail.com>"
name: pattern_finder
description: pattern_finder is a compact library used for signature matching and/or wildcard pattern finder in byte streams.
version: 1.3.1
homepage: https://github.com/ron4fun/pattern_finder
repository: https://github.com/ron4fun/pattern_finder

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  test: ^1.14.4
